default_config:
wake_on_lan:
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  packages: !include_dir_named packages

automation: !include_dir_list automations
script: !include_dir_list scripts
scene: !include scenes.yaml
intent_script: !include intent_script.yaml

ai_tools:

logger:
  default: info
  logs:
    homeassistant.components.conversation: debug
    homeassistant.components.intent: debug
    homeassistant.components.assist_pipeline: debug
    homeassistant.helpers.intent: debug
    custom_components.ai_tools: debug
  filters:
    homeassistant.components.conversation.chat_log:
      - "Received delta:"

# Renew Dev Mode for LG TVs
rest_command:
  renew_lg_tv_tokens:
    url: "https://developer.lge.com/secure/ResetDevModeSession.dev?sessionToken=d8d390c2319cccbd4941bc9e54c0b98ef02273f955e24c10de72f47ba1088d45"
    method: GET