alias: Load Game
description: This automation will load games from a powershell script.
mode: single
triggers:
  - command: load game {game_name}
    trigger: conversation
  - command: load gain {game_name}
    trigger: conversation
  - command: lobe gain {game_name}
    trigger: conversation
  - command: lobe game {game_name}
    trigger: conversation
  - command: load games {game_name}
    trigger: conversation
  - command: load a game {game_name}
    trigger: conversation
  - command: love game {game_name}
    trigger: conversation
  - command: load the game {game_name}
    trigger: conversation
  - command: start game {game_name}
    trigger: conversation
  - command: start games {game_name}
    trigger: conversation
  - command: start gain {game_name}
    trigger: conversation
  - command: start a game {game_name}
    trigger: conversation
  - command: start the game {game_name}
    trigger: conversation
  - command: dark game {game_name}
    trigger: conversation
  - command: low gain
    trigger: conversation
  - command: low game
    trigger: conversation
conditions: []
actions:
  - action: input_text.set_value
    target:
      entity_id: input_text.selected_game
    data:
      value: "{{ trigger.slots.game_name }}"
  - action: button.press
    target:
      entity_id: button.arcade_loadgame
    data: {}
  - action: assist_satellite.announce
    target:
      area_id:
        - playroom
    metadata: {}
    data:
      message: Loading game {{ states('input_text.selected_game') }}
      preannounce: true
      preannounce_media_id:
        media_content_id: media-source://media_source/local/ding-36029.mp3
        media_content_type: audio/mpeg
        metadata:
          title: ding-36029.mp3
          thumbnail: null
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://media_source