alias: Command Test
description: ''
trigger:
  - platform: conversation
    command:
      - load command
condition: []
action:
  - device_id: 4d115df6d13b937d21b8a89d0f471ca1
    domain: button
    entity_id: 7a38ea83699ce5323e78e37140960615
    type: press
    metadata:
      secondary: false
  - service: assist_satellite.announce
    data:
      message: loading command prompt
      preannounce: true
    target:
      area_id: bedroom
mode: single